<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-H0GN5MM" failures="2" tests="2" name="Default test(failed)" time="0.095" errors="0" timestamp="01 Mar 2019 05:32:24 GMT">
  <testcase classname="demo.TestNGFailedTC" name="Test3" time="0.02">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:55)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.Assert.assertTrue(Assert.java:31)
at demo.TestNGFailedTC.Test3(TestNGFailedTC.java:27)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Test3 -->
  <testcase classname="demo.TestNGFailedTC" name="Test2" time="0.004">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at demo.TestNGFailedTC.Test2(TestNGFailedTC.java:19)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="demo.TestNGFailedTC" name="Test1" time="0.0">
    <ignored/>
  </testcase> <!-- Test1 -->
</testsuite> <!-- Default test(failed) -->
